import type { WeddingConfig } from '@/types'

export const DEFAULT_CONFIG: WeddingConfig = {
  id: 1,
  bride_name: 'Adriana',
  groom_name: 'Francisco',
  wedding_date: null,
  ceremony_time: null,
  ceremony_venue: null,
  ceremony_address: null,
  ceremony_maps_url: null,
  reception_time: null,
  reception_venue: null,
  reception_address: null,
  reception_maps_url: null,
  welcome_message: null,
  dress_code: null,
  cover_photo_url: null,
  favicon_url: null,
  gallery_urls: [],
  music_url: null,
  dress_code_image_url: null,
  dress_code_forbidden_text: null,
  dress_code_forbidden_image_url: null,
  seal_image_url: null,
  parents_phrase: 'Con la bendición de nuestros padres',
  bride_parents: null,
  groom_parents: null,
  account_number: null,
  gift_registry_url: null,
  itinerary: [],
  accommodations: [],
  updated_at: new Date().toISOString(),
}
